# production:
# mqUrl=nats://prod-nats.usw2.infovell.com:4222
mqUrl=nats://qa-nats.usw2.infovell.com:4222
mqStreamName=contentOps
# rtu subjects
mqSubjectOut=metaQueue
# TESTING: remove these when done
gcpProject=dd-production
gcsQABucket=rt-upload-staging_qa
gcsProdBucket=rt-upload-staging

